# Generated by Django 5.2 on 2025-04-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jti', models.CharField(max_length=255, unique=True, verbose_name='JTI do token')),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, verbose_name='Revogado em')),
            ],
        ),
    ]
